# Generated by Django 4.2.19 on 2025-03-11 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_blog_thumbnail_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('thumbnail_img', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('thumbnail_url', models.URLField(blank=True, null=True)),
                ('category', models.CharField(default='uncategorized', max_length=255)),
                ('slug', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Blog',
        ),
    ]
